### ISSUE TITLE
Include side bar with detailed filter options?

### ISSUE THREAD

**Issue by T-Engel** [gbif/hp-land#2]
Apologies if this question has come up before. I was just wondering if it is possible to get the full set of filter options available in gbif for our hosted portal. I mean the side bar that appears next to the results:

![image](https://user-images.githubusercontent.com/37897372/208878109-c29e4044-9497-4322-9380-c0678c4e16b8.png)

Does this go beyond the basic functionality of hosted portals envisioned by gbif? 

Of course people can always go to the main gbif site if they want that level of detail, but i think there is some value in having this functionality on the same site that we use to mobilize more datasets for gbif. For example, it would be nice to select a date range or narrow the search down to a specific taxonomic group.

Tagging @MortenHofft  because he was so helpful with a previous issue.
Thanks for the amazing work!

**Comment by jholetschek** [comment]
The full list is available via the "more" button. You can select a year range, for example, or certain years. Taxonomic filters can be added using "scientific name":
![grafik](https://user-images.githubusercontent.com/11058397/208883324-a90771af-d2bf-4307-89bc-d67b7811cdf9.png)

**Comment by jholetschek** [comment]
We can configure which filters appear in the "filter bar" (highlighted filters). That's part of https://helpdesk.gfbio.org/browse/UCASE-84

**Comment by T-Engel** [comment]
Thanks. Yes, I saw this. I just found this side bar much more intuitive and easier to use. For example, with our portal I haven't been able to show all plants in the years 2002-2015, whereas with the side bar on the gbif site this was really easy.

**Comment by jholetschek** [comment]
The filters are the same as in the menu - and they should behave the same, as far as I know. Is that what you wanted to do?
https://land.hp.gbif-staging.org/occurrence/search/?taxonKey=6&view=TABLE&year=2002%2C2015

![grafik](https://user-images.githubusercontent.com/11058397/208886579-a33b1225-93ba-4d95-8507-ba88628c2896.png)

**Comment by T-Engel** [comment]
Great thanks. it now works for me too. The "plantae" I had selected from the drop down menu were labelled as "zweifelhaft" with an orange dot and didnt produce any results.

**Comment by MortenHofft** [comment]
**Available filters**
We might miss some filters still in the hosted portal, if so please create issues for them. The ambition is that all the filters from GBIF.org should be available in the hosted portals as well.

**Sidebar vs top bar**
The layout might change over time  or be configurable, but for now it is the top bar layout that we use for the hosted portals. The sidebar listing all filters had grown so large over time (as new filters were instroduced) that it has become difficult to find what you are looking for. That is the reasoning for replacing it with the more-button and a search.

**Doubtful genera**
It is annoying that there is a doubtful `plantae` genera in the backbone. We have added the orange warnings to indicate that it is suspicious, but perhaps we should spell it out instead of just showing the label on hover. It just takes up a lot of space.

**Date ranges**
I see that the example text that used to be there has been removed. I suspect that has happened in the translation process. I'll take a look at adding it anew.

@T-Engel if you have suggestions for UI changes you are welcome to create an issue - ideally with a detailed drawing/explanation of what to change and how it better accommodates the various scenarios the filter can be used for.
